services:
  # Configured through environment variables
  config-server-env:
    container_name: config-server-coud-sample
    image: "hyness/spring-cloud-config-server:${TAG:-latest}"
    ports:
      - "8888:8888"
    environment:
      # SPRING_CLOUD_CONFIG_SERVER_PREFIX: /config
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/FUCKU/cloudSample
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main  #this is git branch name
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS: '{profile}' #this is search folder name, actually will get {application name} and {application name}-{profile}
